apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-oap
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-oap
  template:
    metadata:
      labels:
        app: skywalking-oap
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
      - name: setup-es-ilm-policy
        image: curlimages/curl:8.4.0
        command:
          - /bin/sh
          - -c
          - |
            set -e

            INDEX_PREFIXES="sw_segment-* sw_zipkin_span-* sw_metrics-all-* sw_records-all-* sw_browser_error_log-* sw_log-*"
            for prefix in $INDEX_PREFIXES; do
              alias=$(echo $prefix | sed 's/-\*.*/''/g' | sed 's/-all//g')
              policy_name="skywalking-policy-$alias"

              echo "Creating or updating ILM policy: $policy_name"
              curl -s -X PUT "http://elasticsearch.monitoring:9200/_ilm/policy/$policy_name" -H 'Content-Type: application/json' -d"
              {
                \"policy\": {
                  \"phases\": {
                    \"delete\": {
                      \"min_age\": \"1d\",
                      \"actions\": {
                        \"delete\": {}
                      }
                    }
                  }
                }
              }"

              echo "Creating or updating index template for: $prefix"
              curl -s -X PUT "http://elasticsearch.monitoring:9200/_template/${alias}-template" -H 'Content-Type: application/json' -d"
              {
                \"index_patterns\": [\"$prefix\"],
                \"settings\": {
                  \"index.lifecycle.name\": \"$policy_name\"
                }
              }"

              echo "---------------------------------------------"
            done

            echo "✅ All ILM policies and index templates created."

      containers:
      - name: oap
        image: apache/skywalking-oap-server:10.1.0
        env:
        - name: SW_STORAGE
          value: elasticsearch
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: elasticsearch.monitoring:9200
        ports:
        - containerPort: 12800
        - containerPort: 11800
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-oap
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: skywalking-oap
  ports:
  - name: http
    port: 12800
    targetPort: 12800
  - name: grpc
    port: 11800
    targetPort: 11800